spring.application.name=ReciclaVille

spring.database.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/reciclaville
spring.datasource.username=postgres
spring.datasource.password=8990

spring.jpa.hibernate.ddl-auto=update
